namespace BuildNotifications.Resources.Icons
{
    public enum IconType
    {
        None,
        Connection,
        Branch,
        Definition,
        BuildNotification,
        Close,
        Maximize,
        Minimize,
        Restore,
        Settings,
        Search,
        Grouping,
        Status,
        AlphabeticalAscending,
        AlphabeticalDescending,
        StatusAscending,
        StatusDescending,
        DateAscending,
        DateDescending,
        GroupingEmpty,
        GroupingSolo,
        Integer,
        Float,
        Text,
        Plus,
        Minus,
        Arrow,
        Dummy,
        Notification,
        SingleBuild,
        Pause
    }
}